### PR TITLE
Update ChartAxisValuesGenerator.swift

### PR DESCRIPTION
**Pull request by bsqdev**
Fixes issue where values are all the same.

### CODE REVIEW

**Comment by i-schuetz** [comment]
Thanks for your contribution! Can you please provide more details about the issue (e.g. steps to reproduce)? Not sure what the problem is.

**Comment by bsqdev** [comment]
If the y axis data is not unique then the first and last values will be the same.  This causes an empty array to be returned for y axis chart values.  I just incremented the last value by 1 in order to get a non-nil array.

**Comment by bsqdev** [comment]
ie y values are [1,1,1,1,1,1,1,1,1,1,1,1,1,1]

**Comment by i-schuetz** [comment]
Ok. Looks like it fixes the issue. The only thing is that it's missing to declare the parameter as `var`, otherwise it doesn't compile.

**Comment by i-schuetz** [comment]
*push push* would you mind adding the `var` to the parameter so I can merge this? Thanks again!

**Pull request merged**
