### PR TITLE
Changed ChartLabelSettings to a struct

### PR DESCRIPTION
**Pull request by NachoSoto**
See #216 for the rationale.

### CODE REVIEW

**Comment by i-schuetz** [comment]
Looking again at this, I'm starting to remember the context. The reason of `let` and `copy` is to enforce immutability. Once you create the instance it's impossible to change it. You just can create a modified copy of it, using `copy`. I don't remember why I used `class` instead of `struct` though. 

Admittedly this pattern leads to verbose implementations, besides of `copy` it's also necessary to write initializers to set default values..

I have recently started moving away from this since I'm getting the feeling it's an overkill in most cases, but not quite sure. If yes it would make sense to change this everywhere, for consistency.

What do you think?

**Comment by NachoSoto** [comment]
> The reason of let and copy is to enforce immutability

You can enforce immutability with `struct`s: since they have value semantics, a `let v: ChartLabelSettings` **is immutable**! Immutability propagates down the type (even if the members are `var`s). This is not true with `class` because making a class variable `let` only affects **the reference**, but not the contents.

Example:
screen shot 2017-02-16 at 3 22 12 pm

**Comment by i-schuetz** [comment]
I know. Back then I was thinking on strict immutability, enforced at library level. You still can mutate a struct declared as var. But you're right in that this isn't really an issue because of the value semantics.

Let's change it then. I'll merge this and do the rest in a while (you can do it too if you want). Thanks!

**Comment by NachoSoto** [comment]
> But you're right in that this isn't really an issue because of the value semantics.

Right, but you can only mutate YOUR copy :)

**Comment by i-schuetz** [comment]
That was what I meant ;)

**Pull request merged**
