### PR TITLE
Straightlinepath no points

### PR DESCRIPTION
**Pull request by creisterer-db**
If the points array was empty a runtime error was generated in the for loop, as the range 0..<-1 is not valid.

Also fixed spelling while I was at it.

### CODE REVIEW

**Comment by i-schuetz** [comment]
Great, thank you! Just one little thing, could you move the `progressLine` settings  also in the if block (and possibly also `closePath`)? If there's no line there's no reason to execute this.

**Comment by i-schuetz** [comment]
This doesn't compile, it seems it's missing to rename the file in pbxproj.

**Comment by creisterer-db** [comment]
@i-schuetz I moved the `progressLine` settings and `closePath` into the if block. I also renamed the file in pbxproj. Sorry about that oversight, not sure how that didn't make it in the commit originally!

**Comment by i-schuetz** [comment]
No problem :) Thanks again!

**Pull request merged**
