### PR TITLE
Feature/#257 zero value track

### PR DESCRIPTION
**Pull request by Fermi37**
It solves the problem with disappearing track values near zero. Some values also have been changed in TrackerExample for demonstration purpose.

### CODE REVIEW

**Comment by i-schuetz** [comment]
Hey,
thanks a lot for taking the time to investigate the issue!
However I'm not sure this fix is the best solution, on one side it introduces 2 additional iterations through all the chart points on each tracker update, which could cause performance issues with charts that have a lot of chart points... not that SwiftCharts is super optimized for performance right now but we don't want to make it worser :) This could be moved at least to initialization or zoom end as there doesn't seem to be a reason to calculate it on each panning delta.

On the other side I'm not sure right now why `view.frame.size.height` is not enough. The tracker line simply has to go from the top to the bottom of the chart and catch the intersections with the chart lines. There should be no need to involve the y position of the chart points in the calculation of the y boundaries.

**Comment by Fermi37** [comment]
I agree with you about a performance of my solution. Initialisation is a better.  Maybe my project has special conditions, that why a have a problem with tracking.

**Comment by i-schuetz** [comment]
It's not your project, it's a bug in the library. The height of the chart area should be enough. I'll give it a look when I have more time. You should be fine until then using a copy of the layer with your fix or linking to your fork.

**Comment by Fermi37** [comment]
Thank you for your time.

**Comment by i-schuetz** [comment]
For now closing this, as it's invalid - bug is still open - no time to fix yet.

**Pull request closed without merging**
