### PR TITLE
Added deployment target for tvOS

### PR DESCRIPTION
**Pull request by LadislavAmbrus**

### CODE REVIEW

**Comment by nonameplum** [comment]
@LadislavAmbrus please resolve conflicts. Have you tried charts with tvOS? No changes needed in code base to work properly with tvOS (focus engine - `canBecomeFocused` etc.)

**Comment by LadislavAmbrus** [comment]
Conflicts resolved. I am using charts with tvOS. Only problem was on `cocoapods install`, therefore I changed .podspec file.

**Comment by LadislavAmbrus** [comment]
Reopeden after closed by accident.

**Comment by i-schuetz** [comment]
Thanks! Could you please squash the commits?

**Comment by i-schuetz** [comment]
Though squashing is actually not correct here, can you rebase to remove 1a79628fe1f3644de1c6e24c395a442d9b2772fb?

**Pull request merged**
