### PR TITLE
Reorganize Project

### PR DESCRIPTION
**Pull request by petester42**
I wanted to contribute to this project by adding a pie chart but I was having trouble understanding the structure of the project. There was a SwiftCharts folder in the root and then also in the example. It was confusing to know where to start to contribute. I reorganized the project so that it is easier to follow and to contribute to. There is a now framework target to compile the framework and the example uses the framework target now instead of having a copy of the source. Should make it easier for anyone wanting to contribute.

Hopefully this helps people to contribute to this awesome library. Great work :+1:

### CODE REVIEW

**Comment by i-schuetz** [comment]
That looks indeed much better, thanks! Only 2 questions: Do we need to keep the Examples.xcodeproj? Why is necessary to import SwiftCharts in the example project files?
Very looking forward to the pie chart :) That's something I always wanted to add but didn't find the time.

**Comment by petester42** [comment]
Examples.xcodeproj is not needed since the example app is in SwiftCharts.xcodeproj. There is no need for duplication. It is necessary to import SwiftCharts into the example project files since the source files are not directly included in the example but as a built framework.

So the example app works like if you were going to use this library in your own app. You would link to framework to your project and then import in the framework in the files you need it in.

**Comment by i-schuetz** [comment]
Ah, my bad, seems my xCode was locking Examples.xcodeproj and when switching branches it let the file there (and git status didn't show anything)... I asked because I thought you didn't remove it. The import part is great, this will also prevent some bugs I had in the past like forgetting to add public identifiers.

**Comment by petester42** [comment]
Ya there was an issue with a missing public when I did the move :p

**Comment by i-schuetz** [comment]
InfoBubble should actually be in the example project - that's why it doesn't have public identifiers. No idea why it's still in the library. Will fix that later.

**Comment by i-schuetz** [comment]
Hey Pierre, btw what happened with the pie chart? Happy to merge this pull request anytime :)

**Comment by petester42** [comment]
I havent had the time yet. The project I've been working on needed pie charts at first but the design changed. I'll get around to it one day :p

**Pull request merged**
