### PR TITLE
Support for syncing touch across multiple charts

### PR DESCRIPTION
**Pull request by loudnate**
Hey @i-schuetz, great library. I required these modifications to the library to achieve the following implementation:
sync-charts

There are two changes:

- Supporting a fixed axis label width
- Creating a new `ChartPointsViewsLayer` leveraging (a potentially shared) `UIGestureRecognizer`. This required some overrides of methods with `internal` access control.

The remaining part of that implementation [can be found here](https://github.com/loudnate/naterade-ios/blob/master/Naterade/Managers/StatusChartManager.swift).

My feelings won't be hurt if you feel like this is too specific of a use case. Just figured I could help give back what's worked well for me.

### CODE REVIEW

**Comment by i-schuetz** [comment]
Hi Nathan,

awesome! No it's not too specific and happy to merge this. Would it be possible to add an example? Otherwise it's difficult to test :) If you do it a screenshot in the readme would also be great.

**Comment by loudnate** [comment]
OK, great! I'll need to find some time to distill an example from the code
I linked to.

**Comment by loudnate** [comment]
Hey @i-schuetz, I've added an example and screenshot as you suggested.

Thanks!

**Comment by loudnate** [comment]
@i-schuetz this is ready for review.

**Comment by i-schuetz** [comment]
Hi Nathan,
awesome, thanks! Sharing the gesture recogniser is a good idea, also like the extension to initialise the layer 👍  everything great! Sorry for the delay.

**Comment by i-schuetz** [comment]
Oops, we should have squashed these commits.

**Pull request merged**
