### PR TITLE
Change alignment of the label on y axis #99

### PR DESCRIPTION
**Pull request by marcinwlodarczyk**
Add textAlignment property to ChartLabelSettings which is used to properly align text in the y axis label

### CODE REVIEW

**Comment by i-schuetz** [comment]
To merge this in the library it would need to satisfy following:

- The alignment should have an effect in the reserved space. If the labels are e.g. aligned right in the left y-axis, the chart should not reserve space on the left.

- The title axis is positioned correctly, which would be next to the divider. The title to labels space setting in this case can be reused as title to line space.

- The space should be correct when using multiple axes. If the labels are e.g. aligned right in the left y-axis, and after it there's another axis left y-axis, this should start after the line and not the space which would have been reserved by the labels on the left side. You also have to take into account that this second axis can have their labels aligned to the left or right. If it has the labels on the right side then it has to start with a distance from the previous axis determined by it's own max labels width.

From what I can see in the implementation I think it's not meeting at least some of these points.

**Comment by marcinwlodarczyk** [comment]
Hi Ivan,
Thanks for your comments - I found a bug in the small piece of logic that I've submitted in this pull request :) With a new commit, now it behaves and renders the labels as it was planned.
And please let me explain what comes with this small request - It's not about changing the side of label axis on which labels are displayed - it' only about aligning the label text to left or right within the same reserved space (based on labelsMaxWidth).

Are you fine with this change now?
Cheers,
Marcin

**Comment by i-schuetz** [comment]
Ah! Sorry. Was thinking about the side indeed. The PR is fine except 2 things - 1. For the implementation to be consistent, it would be good if you can implement this for the right y axes also. 2. I assume you added the "Default" enum value to simplify the settings for the different axes. It's convenient but semantically not quite right as alignment can be only left or right. Default is given by where we use this enum. So if you can find a cleaner way to model this it would be great. Not a must though. Thanks!

**Comment by marcinwlodarczyk** [comment]
It's implemented for ChartAxisYLowLayerDefault and ChartAxisYHighLayerDefault (which I believe is the right y axis) :) - please let me know if I'm wrong.
For the 2nd point I will look into it today.

**Comment by i-schuetz** [comment]
Right, I tested with multiaxes example and set the alignment on the axis titles which has no effect. Sorry for being so distracted, a bit in a hurry lately ;) Then the only point remaining is 2, as I said, if you find this too complicated to implement we can leave it like this.

**Comment by i-schuetz** [comment]
Can I merge this?

**Comment by marcinwlodarczyk** [comment]
Sorry for being not responsive but I was traveling. For the 2nd point I don't see a solution yet how the configuration should be passed which should define when left and when right alignment to choose in current scenarios.
If you could merge the current state of this pull request it would be great since I might not have a time now to come up with a solution :)

**Comment by i-schuetz** [comment]
Hi Marcin,
no problem! About the default values, actually UIKit also uses this quite a lot so I guess it's at least consistent :) Thanks for your contribution!

**Comment by marcinwlodarczyk** [comment]
Thank a lot! :)

**Pull request merged**
