### PR TITLE
Support Swift Package Manager in Xcode 11

### PR DESCRIPTION
**Pull request by Matovsky**
Support Swift Package Manager in Xcode 11 https://github.com/i-schuetz/SwiftCharts/issues/399

### CODE REVIEW

**Comment by groapp** [comment]
@Matovsky  - nice work on the Package.swift. When I clone your repo into SPM in XCode everything works fine; however, if I copy and paste the code from your Package.swift file into my own fork of the latest release I get the dreaded "no Package.swift manifest for version 0.6.5" error. Any ideas?

**Comment by Matovsky** [comment]
Thank you. Well, here I have no idea. Because in Xcode 11.x we can just go to File > Swift Packages > Add Package Dependency. That is 👍🏻 By the way, in my opinion, with SwiftUI we don't need this kind of libraries anymore. SwiftUI makes amazing charts and animation.

**Comment by i-schuetz** [comment]
Sorry, I missed this.

**Comment by i-schuetz** [comment]
Uh, for clarity, is this file still needed? I've been only on the user side of SPM projects and not sure what the library has to do.

**Pull request merged**
